default: &default
  domain: "http://mailhok.solife.us"
  admins: "jay_li@intfocus.com;albert_li@intfocus.com"
  regexp:
    order: "^ppc\\d+u\\d+o[a-zA-Z]{3}$"
    order_item: "^ppc\\d+u\\d+o\\d+i[a-zA-Z]{3}$"
  weixin:
    name: "名片转家"
    desc: "TODO"
  website:
    title: "名片转家"
    subtitle: "Carder"
    slogan: "名片转家"
    favicon: "/images/favicon.ico"
  api:
    v1:
      url: "http://mailhok.solife.us/track"
  alipay:
    pid: '2088802087947025' 
    secret: '15piw6e1bp612r4p1sxcl7yqxvupryy2'
    seller_email: "jay_li@solife.us" 
    return_url: "http://mailhok.solife.us/transactions/done"
    notify_url: "http://mailhok.solife.us/transactions/notify"
  cdn:
    qiniu:
      bucket: "carder-cdn"
      access_key: 'gPQo6zcUBMtLdXGWl2A3VK-zchb2LXzZhfWtWsou'
      secret_key: 'whGyzlD1xwaT4VbyEQ81B51ROWqIPTSlI4iXeY1-'
      out_link: "http://carder-cdn.qiniudn.com"

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  default_password: ''
